name: Build and deploy AWS lambda
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Lint & Format
        run: pnpm check
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Create Zip package
        run: |
          zip -r build-${{ github.sha }}.zip package.json
          zip -r build-${{ github.sha }}.zip index.js
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload zip to s3
        run: aws s3 cp build-${{ github.sha }}.zip s3://artifacts-lambda-2023
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: AddressService
          zip_file: build-${{ github.sha }}.zip
